### PR TITLE
Added uboot patch to fix build error in gcc 10

### LINKED ISSUE #6: linker error in u-boot with gcc 10.
First off, thanks for creating this!

I was trying it out (going to take a stab at adding support for #1), and I got a build error in u-boot when compiling v0.1.1:

```
/usr/bin/ld: scripts/dtc/dtc-parser.tab.o:(.bss+0x10): multiple definition of `yylloc'; scripts/dtc/dtc-lexer.lex.o:(.bss+0x0): first defined here                                            
collect2: error: ld returned 1 exit status                                                                                                                                                    
make[4]: *** [scripts/Makefile.host:106: scripts/dtc/dtc] Error 1                                                                                                                             
make[3]: *** [scripts/Makefile.build:432: scripts/dtc] Error 2                                                                                                                                
make[2]: *** [Makefile:515: scripts] Error 2                                                                                                                                                  
make[1]: *** [package/pkg-generic.mk:250: /home/andrew/repos/nerves_system_npi_imx6ull/.nerves/artifacts/nerves_system_npi_imx6ull-portable-0.1.1/build/uboot-d447c4866200ae5fd069313d92e2308f
f01af021/.stamp_built] Error 2                                                                                                                                                                
make: *** [Makefile:23: _all] Error 2                                                                                                                                                         
```

After some googling, I found that gcc 10 defaults to -fno-common, which causes the above error during linking u-boot. It's been fixed in upstream u-boot, but not in the NPi i.MX6ULL branch. I've taken the patch from u-boot that fixes the issue: https://gitlab.denx.de/u-boot/u-boot/-/commit/018921ee79d3f30893614b3b2b63b588d8544f73 and added it to the uboot patches directory. If you'd rather handle it a different way, then let me know.

### PR DESCRIPTION
**Pull request by aadavids**
Resolves #6 .

### CODE REVIEW

**Comment by fhunleth** [comment]
So this is super nice since Justin Schneck is working on gcc 10 toolchains for Nerves, but we haven't released them yet. Unless you changed the `nerves_defconfig` to use an alternative toolchain, this should still use gcc 9. Could you confirm that  you're using gcc 10?

**Comment by aadavids** [comment]
So the strange part is that I haven't changed the toolchain in nerves_defconfig, but I do have gcc 10 installed natively on my laptop. I reverted to gcc-9, and the error went away, without the patch to u-boot. But I don't think that should have affected the build of the nerves system, so I'll have to double check my setup.

**Comment by fhunleth** [comment]
I looked at the error again and I understand what's going on now. This is for the host build of u-boot related tools and not for anything running on the imx6ull. That's why it's using your host gcc. A whole lot of people are going to run into this issue for other Nerves systems as soon as gcc 10 gets installed in more places. Thank you!!

I'm going to see if there's a more central place that I can put the patch, but if not, I'll be merging this.

**Comment by fhunleth** [comment]
Ok. Looks good. Thanks!

**Comment by aadavids** [comment]
> I looked at the error again and I understand what's going on now. This is for the host build of u-boot related tools and not for anything running on the imx6ull. That's why it's using your host gcc. A whole lot of people are going to run into this issue for other Nerves systems as soon as gcc 10 gets installed in more places. Thank you!!
> 
Oh I see, that makes sense now. Thanks!

**Pull request merged**
